### PR TITLE
Added pinterest support, facebook share dialog, google snippets, reactivity

### PR DESCRIPTION
**Pull request by lovetostrike**
Changes:
- added pinterest
- added googleplus snippets
- added facebook share dialog for apps with valid id
- replaced meteor.startup because we might not want it to init on every page, now it requires explicit init 
- silenced fb-root div warning
- added reactivity to rerun whenever the data changes
- looping of templates
- updated the tests

Let me know what you think works and what doesn't. Thanks :)

### CODE REVIEW

**Comment by rgoomar** [comment]
@queso You should merge this in :+1:

**Comment by queso** [comment]
@rgoomar have you tested it in an app yet?

**Comment by rgoomar** [comment]
Not just yet, but from going through the code, the logic seems to be in place and I don't see why it should break anything really. I can test it later tonight though.

**Comment by queso** [comment]
That would be awesome, my main focus is velocity atm and I will be wrapped up in that all night.

**Comment by Nullpo** [comment]
+1

**Comment by elie222** [comment]
Need to add to the README that init is now explicitly required. Plus googleplus color is broken.

**Pull request merged**
